pull_request_rules:
# pre-commit ci won't automerge (see https://github.com/pre-commit-ci/issues/issues/48)
- name: automatic merge for pre-commit ci updates
  conditions:
  - author=pre-commit-ci[bot]
  - title=[pre-commit.ci] pre-commit autoupdate
  actions:
    merge:
      method: squash
